### ISSUE TITLE
ubuntu 20.04 python3 install issue

### ISSUE THREAD

**Issue by Timple** [git-afsantos/hpl-specs#5]
```
$ pip install --user haros
Collecting haros
  Downloading haros-3.10.4.tar.gz (323 kB)
     |████████████████████████████████| 323 kB 5.4 MB/s 
Collecting bonsai-code<1.0.0,>=0.5.0
  Downloading bonsai-code-0.6.3.tar.gz (39 kB)
Collecting haros-plugins<2.0.0,>=1.0.3
  Downloading haros_plugins-1.1.4.tar.gz (83 kB)
     |████████████████████████████████| 83 kB 903 kB/s 
Collecting hpl-specs
  Downloading hpl-specs-0.2.1.tar.gz (26 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-e4ecxw11/hpl-specs/setup.py'"'"'; __file__='"'"'/tmp/pip-install-e4ecxw11/hpl-specs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-e4ecxw11/hpl-specs/pip-egg-info
         cwd: /tmp/pip-install-e4ecxw11/hpl-specs/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-e4ecxw11/hpl-specs/setup.py", line 24, in <module>
        requirements = [r for r in read("requirements.txt").splitlines() if r]
      File "/tmp/pip-install-e4ecxw11/hpl-specs/setup.py", line 18, in read
        with open(os.path.join(os.path.dirname(__file__), fname)) as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-e4ecxw11/hpl-specs/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Miniature Dockerfile for reproduction:
```Dockerfile
FROM ubuntu:20.04
RUN apt update -qq && apt install -qqy python3-pip
RUN pip install haros
```

**Comment by git-afsantos** [comment]
Thanks for reporting this issue @Timple. The fault was actually present in a few other repositories, so I have taken the opportunity to fix them all. The fix was committed in https://github.com/git-afsantos/hpl-specs/commit/2271115b4602172db64438a8eeb739e56e5e656e and released in [HPL v0.2.2](https://github.com/git-afsantos/hpl-specs/releases/tag/v0.2.2).

With the fix, I was able to build the Docker image you provided without problems, and was even able to import the packages to Python3 within a container. Let me know if the issue still persists on your side.

**Comment by git-afsantos** [comment]
Closing the issue due to lack of activity; will reopen if necessary.

**Comment by Timple** [comment]
Ah, yes. This worked :)
